profile = "C:\\Users\\Matthew\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\khs64xww.remote"
screenshot_path = "C:\\Users\\Matthew\\Desktop\\scraper\\screenshots\\"
marionette_port = 28287

timeout = 60000 # 60 seconds

# each group gets its own window
# restart closes and re-opens all windows
groups = [
    { name = "amazon", steps = [
        { action = { Navigate = { url="https://www.amazon.com/AMD-Ryzen-5900X-24-Thread-Processor/dp/B08164VTWH", anti_cache=true } }, logging=false},
        #{ action = { Navigate = { url="https://www.amazon.com/AMD-Ryzen-3900XT-24-Threads-Processor/dp/B089WD454D" }}, logging=false},
        #{ action = { Navigate = { url="https://www.amazon.com/AMD-Ryzen-3800X-16-Thread-Processor/dp/B07SXMZLPJ/" }}, logging=false},
        #{ action = { Navigate = { url="https://www.amazon.com/dp/B000YSONMO/" }}, logging=false},
        #{ action = "Refresh", logging=false },
        # { action = "Screenshot" },

        # check for captcha
        { name="captcha_check", delay=100, action = { MatchUrl = "amazon.com/errors/validateCaptcha"}, optional=true, logging=false},
        { name="captcha_solve", delay=5000, action = { Special = "SolveAmazonReCaptcha"}, if_cond="captcha_check",optional=true},

        { name="buy_now", action = { Find = {selector="#buy-now-button", action= "Click" }}, logging=false, optional=true},
        { name="delay", action = { Wait = 5000 } , logging=false, if_not_cond="buy_now"},
        { name="early_end", action = "End", logging=false, if_not_cond="buy_now"},

        { name="no_thanks", delay=1200, action = { Find = { selector="#siNoCoverage-announce", action= "Click" }}, optional=true},

        # early stop if sent to cart page
        { name="cart_early", delay=200, action = { MatchUrl = "amazon.com/gp/cart/"}, optional=true},
        { name="cart_early_end", action = "End", if_cond="cart_early"},

        { name="place_order_frame", delay=1200, action = { Find = { selector="#turbo-checkout-iframe", action="SwitchFrame" }}, optional=true},
        { name="place_order_modal", wait_max=2500, delay=1000, action = { Find = { selector="#turbo-checkout-pyo-button", action="Click" }}, if_cond="place_order_frame"},

        { name="place_order_page", delay=1000, action = { Find = { selector="input[name='placeYourOrder1']", action="Click" }}, if_not_cond="place_order_frame"},
        { name="no_order_page", action = "End", if_not_cond="place_order_page"},

        { name="verify_order", wait_max=2100, delay=1000, action = { MatchUrl = "amazon.com/gp/buy/thankyou/"}},
    ]},

    # { name = "test", steps = [
    #     { name="navigate", action = { Navigate = { url="https://www.amazon.com/errors/validateCaptcha"} }},
    #     { name="solve", action = { Special = "SolveAmazonReCaptcha"} },
    #     { name="end", action = "End", delay=10000 },
    # ]},
]