restart = 1800000 # 30 minutes
timeout = 10000

# each group gets its own window
# restart closes and re-opens all windows
groups = [
    { name = "amazon", startup=[
        { Navigate = "https://www.amazon.com/gp/sign-in.html" },
        { Find = { name="username", selector="#ap_email", action={Insert="amazon_username"} }},
        { Find = { name="continue", selector="#continue", action="Click" }},
        #{ Find = { name="remember", selector="input[name='rememberMe']", action="Click"}},
        { Find = { name="password", selector="#ap_password", action={Insert="amazon_password"} }},
        { Find = { name="signin", selector="#signInSubmit", action= "Click" }},
    ], steps = [
        { Wait = 5000 },
        { Navigate = "https://www.amazon.com/AMD-Ryzen-5900X-24-Thread-Processor/dp/B08164VTWH" },
        "Refresh",

        #{ Navigate = "https://www.amazon.com/AMD-Ryzen-3900XT-24-Threads-Processor/dp/B089WD454D" },
        #{ Find = { name="price_check", selector="#price_inside_buybox", action={Compare={Equal="$13.99"}} }},
        { Find = { name="buy_now", selector="#buy-now-button", action= "Click", logging=false }},
        { Log = "IN STOCK" },
        { Find = { name="no_thanks", selector="#siNoCoverage-announce", action= "Click", wait_max=3000, delay=1000 }},

        { Find = { name="place_order", selector="input[name='placeYourOrder1']", action="Click", wait_max=7000, delay=3000 }},
        
        #{ Find = { name="verify_purchase", selector="", action="None" }},
        { Log = "success" },
    ]},

    # { name = "newegg", startup=[
    #     { Navigate = "https://www.newegg.com/amd-ryzen-9-5900x/p/N82E16819113664" },
    # ], steps = [
    #     { Wait = 5000 },
    #     { Navigate = "https://www.newegg.com/amd-ryzen-9-5900x/p/N82E16819113664" },
    #     "Refresh",
    #     { Find = { name="buy_now", selector="#buy-now-button", action= "Click", logging=false }},
    # ]},
]